#!/bin/bash
set -euo pipefail

cd $(dirname $0)/../..

NOTO_CJK_SRC=core/assets-src/fonts/NotoSansCJK-Regular.ttc
PO_DIR=android/assets/po

# Generate a subset of NotoSansCJK containing only the glyphs we need. This
# drastically reduces the size of the files to ship.

# ATTENTION: pyftsubset requires `=` between an option and its value!
pyftsubset \
    --text-file=$PO_DIR/zh_CN.po \
    $NOTO_CJK_SRC \
    --font-number=2 \
    --output-file=android/assets/fonts/NotoSansCJK-subset.otf
