#!/bin/sh
set -e

if [ ! -e CMakeLists.txt ] ; then
    echo "Looks like '$PWD' is not a source tree"
    exit 1
fi

mkdir -p build
cd build
cmake -DENABLE_UI=OFF -DCMAKE_BUILD_TYPE=MinSizeRel -G Ninja ..
ninja aseprite
ninja install
