/*
 * Copyright 2014 Aurélien Gâteau <mail@agateau.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.agateau.translations;

/**
 * Implementation of Translator.Implementation which uses translation classes generated by
 * tools/po-compile
 */
public class GettextImplementation implements Translator.Implementation {
    // When an entry has a context, the generated key is:
    // {msgid}{CONTEXT_SEPARATOR}{msgctx}
    private static final String CONTEXT_SEPARATOR = "!!!";
    private final Messages mMessages;

    private GettextImplementation(Messages messages) {
        mMessages = messages;
    }

    /**
     * Tries to load an implementation for the given languageId
     *
     * <p>languageId must be of the form {lang} or {lang}_{territory}
     */
    public static GettextImplementation load(String languageId) {
        Messages messages = tryLoad(languageId);
        if (messages == null) {
            return null;
        }
        return new GettextImplementation(messages);
    }

    @Override
    public String trc(String src, String context) {
        if (mMessages == null) {
            return src;
        }
        String key = context == null ? src : (src + CONTEXT_SEPARATOR + context);
        String txt = mMessages.plainEntries.get(key);
        return txt == null ? src : txt;
    }

    @Override
    public String trn(String singular, String plural, int n) {
        String txt = findPluralTranslation(singular, plural, n);
        if (txt == null) {
            txt = n == 1 ? singular : plural;
        }
        return txt.replace("%#", String.valueOf(n));
    }

    private String findPluralTranslation(String singular, String plural, int n) {
        if (mMessages == null) {
            return null;
        }
        Messages.PluralId id = new Messages.PluralId(singular, plural);
        String[] lst = mMessages.pluralEntries.get(id);
        if (lst == null) {
            return null;
        }
        return lst[mMessages.plural(n)];
    }

    private static Messages tryLoad(String suffix) {
        Class<?> cls;
        try {
            cls = Class.forName("com.agateau.translations.Messages_" + suffix);
        } catch (ClassNotFoundException exception) {
            return null;
        }

        try {
            return (Messages) cls.newInstance();
        } catch (InstantiationException | IllegalAccessException ignored) {
        }
        return null;
    }
}
