#!/usr/bin/env python3
"""
Display info about an aseprite file
"""
import argparse
import sys

from aseprite import AsepriteImage


def main():
    parser = argparse.ArgumentParser()
    parser.description = __doc__

    parser.add_argument("ase_file")

    args = parser.parse_args()

    image = AsepriteImage(args.ase_file)

    print(f"size={image.size[0]}x{image.size[1]}")
    print(f"depth={image.depth}")
    print(f"color_count={image.color_count}")
    print(f"frame_count={image.frame_count}")
    print(f"transparent_color={image.transparent_color}")
    print("# layers")
    for idx, layer in reversed(list(enumerate(image.layers))):
        print(f"{idx}: {layer.name:40} visible={layer.visible} group={layer.is_group}")
    print("# palette (RGBA)")
    for idx, color in enumerate(image.palette):
        r, g, b, a = color
        print(f"{idx:3}: #{r:02x}{b:02x}{g:02x}{a:02x}")
    print("# slices")
    for slice_ in image.slices:
        print(f"{slice_.name:40} pos={slice_.position} size={slice_.size}")


    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
