name: main

on:
  pull_request:
  push:
    branches:
      # Only build on push for master or dev, otherwise branches pushed for PR
      # are built twice
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: ci/build-docker-image
        shell: bash
      - name: Build
        shell: bash
        run: ci/docker-build-game SNAPSHOT=1
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Smoke tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: make smoke-tests SNAPSHOT=1

      - name: Upload
        # Do not upload for pull requests: `make upload` does not work without the upload secrets
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: make upload SNAPSHOT=1
        env:
          UPLOAD_USERNAME: ${{ secrets.UPLOAD_USERNAME }}
          UPLOAD_PRIVATE_KEY: ${{ secrets.UPLOAD_PRIVATE_KEY }}
          UPLOAD_HOSTNAME: ${{ secrets.UPLOAD_HOSTNAME }}
